user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

base:
    resource: "@BaseBundle/Resources/config/routing.yml"
    prefix:   /public
