<?php

namespace BaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SubCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCardRepository extends EntityRepository
{
}
