<?php

namespace BaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserConsumptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserConsumptionRepository extends EntityRepository
{
}
